"""
Tomorrow's Plan generator and approval flow.

Generates immediately after the EOD report on every COFOUNDER day.
The plan is a structured JSON card pushed to the SwiftUI app.

The agent is FULLY HALTED on next-day execution until the founder
approves via POST /plan/approve. On approval, the rotation pointer
advances and the plan is loaded into LangGraph state.

On POST /plan/revise, the agent re-queues plan generation with
the founder's directive as additional context.
"""

from __future__ import annotations

import json
import logging
import os
from datetime import date, datetime
from typing import TypedDict

import asyncpg
from openai import AsyncOpenAI

from foundry import build_suggestion, load_state, advance_rotation, log_override
from notifications.apns import send_eod_report

logger = logging.getLogger(__name__)
oai = AsyncOpenAI(api_key=os.environ["OPENAI_API_KEY"])

CREATE_PLAN_TABLE = """
CREATE TABLE IF NOT EXISTS daily_plans (
    id               SERIAL PRIMARY KEY,
    plan_date        DATE        NOT NULL DEFAULT CURRENT_DATE,
    plan_json        JSONB       NOT NULL,
    status           TEXT        NOT NULL DEFAULT 'pending',
    founder_note     TEXT,
    approved_at      TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (plan_date)
);
"""


class PlanTask(TypedDict):
    division:             str    # Software | Hardware | Integration | Brand | Learning
    description:          str
    estimated_risk:       str    # low | medium | high
    tools_required:       list[str]
    physical_deliverable: str    # exists | needed | n/a
    is_rotation_task:     bool
    rotation_rationale:   str | None


class DailyPlan(TypedDict):
    plan_date:          str
    rotation_suggestion: dict    # FoundrySuggestion
    tasks:              list[PlanTask]
    status:             str      # pending | approved | revised
    founder_note:       str | None


async def generate_plan(
    conn: asyncpg.Connection,
    eod_context: dict,
    revision_directive: str | None = None,
) -> DailyPlan:
    """
    Generate tomorrow's plan and persist it as 'pending'.

    The rotation suggestion is the first task slot. The remaining
    2–4 tasks are generated by o4-mini based on EOD context and
    current Cycle 2 priorities.

    revision_directive: if set, this is a re-generation triggered
    by POST /plan/revise. The directive is injected into the prompt.
    """
    await conn.execute(CREATE_PLAN_TABLE)

    rotation_state = await load_state(conn)
    suggestion     = build_suggestion(rotation_state)
    plan_date      = (date.today()).isoformat()

    tasks = await _generate_tasks(suggestion, eod_context, revision_directive)

    plan = DailyPlan(
        plan_date=plan_date,
        rotation_suggestion=dict(suggestion),
        tasks=tasks,
        status="pending",
        founder_note=None,
    )

    # Upsert: if a plan already exists for today (e.g. a revision),
    # replace it so the app always shows the latest version.
    await conn.execute(
        """
        INSERT INTO daily_plans (plan_date, plan_json)
        VALUES ($1, $2::jsonb)
        ON CONFLICT (plan_date) DO UPDATE
        SET plan_json  = EXCLUDED.plan_json,
            status     = 'pending',
            created_at = NOW()
        """,
        plan_date,
        json.dumps(plan),
    )

    logger.info("[PLAN] Generated plan for %s — %d tasks", plan_date, len(tasks))
    return plan


async def approve_plan(
    conn: asyncpg.Connection,
    plan_date: str,
) -> DailyPlan:
    """
    Called by POST /plan/approve.

    1. Marks the plan as approved.
    2. Advances the Rotation Cycle pointer.
    3. Returns the approved plan so the LangGraph thread can resume.
    """
    await conn.execute(CREATE_PLAN_TABLE)
    await conn.execute(
        """
        UPDATE daily_plans
        SET status = 'approved', approved_at = $1
        WHERE plan_date = $2
        """,
        datetime.utcnow(),
        plan_date,
    )
    await advance_rotation(conn)

    row = await conn.fetchrow(
        "SELECT * FROM daily_plans WHERE plan_date = $1", plan_date
    )
    plan = json.loads(row["plan_json"])
    plan["status"] = "approved"
    logger.info("[PLAN] Approved plan for %s — rotation advanced", plan_date)
    return plan


async def revise_plan(
    conn: asyncpg.Connection,
    plan_date: str,
    founder_directive: str,
    eod_context: dict,
) -> DailyPlan:
    """
    Called by POST /plan/revise.

    Logs a rotation override (the founder's directive implies
    they don't want the suggested rotation step), then re-generates
    the plan with the directive as a constraint.
    """
    await log_override(
        conn,
        reason="Founder requested plan revision",
        founder_directive=founder_directive,
    )
    revised = await generate_plan(conn, eod_context, revision_directive=founder_directive)
    revised["founder_note"] = founder_directive
    revised["status"]       = "revised"

    await conn.execute(
        """
        UPDATE daily_plans
        SET plan_json    = $1::jsonb,
            status       = 'revised',
            founder_note = $2
        WHERE plan_date  = $3
        """,
        json.dumps(revised),
        founder_directive,
        plan_date,
    )
    logger.info("[PLAN] Revised plan for %s with directive: %s", plan_date, founder_directive[:80])
    return revised


async def get_plan(conn: asyncpg.Connection, plan_date: str) -> DailyPlan | None:
    """Fetch a specific day's plan — used by SwiftUI GET /plan/{date}."""
    await conn.execute(CREATE_PLAN_TABLE)
    row = await conn.fetchrow(
        "SELECT * FROM daily_plans WHERE plan_date = $1", plan_date
    )
    if not row:
        return None
    plan = json.loads(row["plan_json"])
    plan["status"]       = row["status"]
    plan["founder_note"] = row["founder_note"]
    return plan


# ── o4-mini task generation ────────────────────────────────────────────────────

async def _generate_tasks(
    suggestion: dict,
    eod_context: dict,
    revision_directive: str | None,
) -> list[PlanTask]:
    revision_block = (
        f"\nFOUNDER DIRECTIVE (mandatory constraint): {revision_directive}\n"
        if revision_directive else ""
    )

    prompt = f"""
You are APEX-AGENT's planning engine for Veynor (Cycle 2: Hardening).

Generate 3–5 prioritized tasks for tomorrow. Return ONLY a JSON array of task objects.
No explanation. No markdown. Raw JSON only.

ROTATION CYCLE SUGGESTION (this MUST be the first task):
  Current phase: {suggestion['current_phase']}
  Suggested next: {suggestion['suggested_next_phase']}
  Rationale: {suggestion['rationale']}
  Cycle 2 context: {suggestion['cycle_2_context']}
  Physical deliverable required: {suggestion['physical_deliverable_required']}
  Physical deliverable note: {suggestion['physical_deliverable_note']}
{revision_block}
EOD CONTEXT:
{json.dumps(eod_context, indent=2)}

Each task object must have exactly these keys:
  division             (Software | Hardware | Integration | Brand | Learning)
  description          (one sentence, specific and actionable)
  estimated_risk       (low | medium | high)
  tools_required       (list of strings)
  physical_deliverable (exists | needed | n/a)
  is_rotation_task     (true for the first task only)
  rotation_rationale   (one sentence for the first task, null for others)

Constraints:
- First task is always the rotation suggestion.
- Cycle 2 Hardening: Software tasks must target deterministic performance.
  Hardware tasks must advance PCB / DFM. Integration tasks must reduce latency.
- If physical_deliverable is 'needed', the description must include producing it.
- No vague tasks ("improve performance"). Every task must be completable in one day.
"""

    resp = await oai.chat.completions.create(
        model="o4-mini",
        messages=[
            {"role": "system", "content": "You are a planning engine. Output only valid JSON."},
            {"role": "user",   "content": prompt},
        ],
        response_format={"type": "json_object"},
    )

    raw = json.loads(resp.choices[0].message.content)
    # The model wraps the array in a key — extract it.
    tasks_raw = raw if isinstance(raw, list) else next(iter(raw.values()))
    return [PlanTask(**t) for t in tasks_raw]
